### ISSUE TITLE
Claims Failing

### ISSUE THREAD

**Issue by SurfBitHub** [drignads/PCS-PREDICTION-MULTI_STRATEGY-BOT#8]
Hi,
I get this message error then trying to collect winnings.

Attempting to claim 1 rounds...%
 [46854]
/Users/master/Library/Python/3.8/lib/python/site-packages/web3/eth.py:633: UserWarning: There was an issue with the method eth_maxPriorityFeePerGas. Calculating using eth_feeHistory.
  warnings.warn(
Restarting...% {'code': -32601, 'message': 'the method eth_feeHistory does not exist/is not available'}

Please, do you know how to fix it ?

Thank you

**Comment by drignads** [comment]
check new release :)
